[package]
name = "wuerfel"
version = "0.1.0"
edition = "2021"

[dependencies]
getargs = "0.5.0"
getrandom = { version = "0.2.15", default-features = false }
oorandom = "11.1.4"
ratatui = { version = "0.28.1", features = ["all-widgets"] }
